// Code generated by GitHub Actions during release. DO NOT EDIT.
// This file is automatically updated when a release tag is pushed.
package main

// Version information embedded at build time by GitHub Actions
var (
	embeddedVersion = "dev"
	embeddedCommit  = "none"
	embeddedDate    = "unknown"
)

