// Code generated by GitHub Actions during release. DO NOT EDIT.
// This file is automatically updated when a release tag is pushed.
package main

// Version information embedded at build time by GitHub Actions
var (
  embeddedVersion = "v0.1.6"
  embeddedCommit  = "9337ecc"
  embeddedDate    = "2025-11-18T07:38:24Z"
)
