// Code generated by GitHub Actions during release. DO NOT EDIT.
// This file is automatically updated when a release tag is pushed.
package main

// Version information embedded at build time by GitHub Actions
var (
  embeddedVersion = "v0.2.0"
  embeddedCommit  = "da37c8d"
  embeddedDate    = "2025-11-18T14:38:09Z"
)
